# Vim
# vim: set filetype=ruby:
# vim: set ft=ruby:
#
# Emacs
# -*- mode: ruby; -*-

VAGRANTFILE_API_VERSION = "2"
MAX_MEMORY = 1024
SHOW_GUI = true

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    # Vagrant box to build on
    config.vm.box = "drmyersii/ubuntu-desktop-14.04-x64"
    config.vm.box_url = "https://atlas.hashicorp.com/drmyersii/boxes/ubuntu-desktop-14.04-x64/versions/1.0.0/providers/virtualbox.box"

    # settings for VirtualBox provider
    config.vm.provider "virtualbox" do |v|
        v.memory = MAX_MEMORY
        v.gui = SHOW_GUI
    end

    # call provisioner
    config.vm.provision :shell, inline: "cd /vagrant && ./provision.sh", privileged: false
end
